version: "3.7"
# version: "2.4"

services:
  ################################################################################
  # NGINX
  ################################################################################
  nginx:
    image: nginx:latest
    #image: jwilder/nginx-proxy
    container_name: nignx_reverse_proxy
    restart: unless-stopped
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

    healthcheck:
      test: service nginx status || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  ##############################################################################
  # Vault
  ##############################################################################
  vault:
    container_name: vault_latest
    image: vault:latest
    #builds from static docker file instead of "latest" image that could compromise the whole deployment health in a prod enviroment.
    # build:
    #   context: ./
    #   dockerfile: Vault.dockerfile
    restart: unless-stopped

    environment:
      #- "VIRTUAL_HOST=www.example.com"
      - "VIRTUAL_PROTO=http"
      - "VIRTUAL_PORT=80"
      - "HTTPS_METHOD=redirect"

    volumes:
      - ./vault/vault-server.hcl:/vaultserver/config/vault-server.hcl

    ports:
      # <Port exposed> : <Vault Port running inside container>
      - "8200:8200"

    #RAM ONLY
    cap_add:
      - IPC_LOCK
    
    command: "server -config /vaultserver/config/vault-server.hcl"
    # command: "server -dev"

  ################################################################################
  # Mysql
  ################################################################################
  db:
    container_name: mysql_latest
    image: mysql:latest
    restart: unless-stopped

    ports:
      # <External port mapping> : <internal port mapping>
      - "3306:3306"

    expose:
      #Opens port 3306 on the container
      - "3306"
    
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASS: secret
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
      MYSQL_DATABASE: vault
    
    #volumes:
     # - my-db:/var/lib/
      
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5