version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nignx_reverse_proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  vault:
    container_name: vault_latest
    image: vault:latest
    ports:
      - "8200:8200"
    volumes:
      - ./vault/vault-server.hcl:/vaultserver/config/vault-server.hcl
    command: "server -config /vaultserver/config/vault-server.hcl"